using TestProject.Common.DTO.ExecutionResult;
using TestProject.Common.Enums;
using System;
using TestProject.SDK;

namespace TestProject.Generated.Tests.JohnLewisPurchaseFlow
{
    /// <summary>
    /// This class was automatically generated by TestProject
    /// Provides an example how to run coded TestProject tests
    /// </summary>
    public class JohnLewisTestProjectRunner
	{
		public static string DevToken = "TINv6YdnQr8JybiOLiu7QtWUhSmVNk2Si7BwdIYqAc8";
		public static AutomatedBrowserType Browser = AutomatedBrowserType.Chrome;
		public static StepExecutionResult RunJohnlewispurchaseflow()
		{
			using (var runner = new RunnerBuilder(DevToken).AsWeb(Browser).Build())
				return runner.Run(new Johnlewispurchaseflow(), true);
		}

		public static void Main(string[] args)
		{
			try
			{
				RunJohnlewispurchaseflow();
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex);
			}
		}
	}
}